name: Verification build

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "test/**"

permissions: write-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          TZ: UTC+13
          PGTZ: UTC+13
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      yugabyte:
        image: yugabytedb/yugabyte:latest
        env:
          TZ: Etc/GMT-13
          PGTZ: Etc/GMT-13
        options: >-
          --health-cmd postgres/bin/pg_isready -h yugabyte -p 5433 -U yugabyte
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5433:5433

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test-PSQL
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults.PostgreSql.trx"
      - name: Test-YSQL
        env:
          Hangfire_PostgreSql_ConnectionString: "Server=127.0.0.1;Port=5433;Database=yugabyte;User Id=yugabyte;Password=yugabyte;"
          Hangfire_Yugabyte_Mode: true
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults.Yugabyte.trx"
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: "**/TestResults.*.trx"
